spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: vat-rates-service
          predicates:
            - Path=/msg/vat-rates/**
          uri: lb://vat-rates-service
          filters:
            - RewritePath=/msg/vat-rates/(?<segment>.*),/vat-rates/$\{segment}
server:
  port: 9000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:9001/eureka/
